version: 2

models:
  - name: stg_br_stocks
    columns:
      - name: ticker
        tests:
          - unique
          - not_null
      - name: companyname
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: p_l
      - name: p_vp
      - name: p_ebit
      - name: p_ativo
      - name: ev_ebit
      - name: margembruta
      - name: margemebit
      - name: margemliquida
      - name: p_sr
      - name: p_capitalgiro
      - name: p_ativocirculante
      - name: giroativos
      - name: roe
      - name: roa
      - name: roic
      - name: dividaliquidapatrimonioliquido
      - name: dividaliquidaebit
      - name: pl_ativo
      - name: passivo_ativo
      - name: liquidezcorrente
      - name: peg_ratio
      - name: receitas_cagr5
      - name: vpa
      - name: lpa
      - name: valormercado
      - name: segmentid
      - name: sectorid
      - name: subsectorid
      - name: dy
        tests:
          - not_null
      - name: lucros_cagr5
        tests:
          - not_null
      - name: market

  - name: stg_us_stocks
    columns:
      - name: ticker
        tests:
          - unique
          - not_null
      - name: companyname
        tests:
          - not_null
      - name: price
        tests:
          - not_null
      - name: p_l
      - name: p_vp
      - name: p_ebit
      - name: p_ativo
      - name: ev_ebit
      - name: margembruta
      - name: margemebit
      - name: margemliquida
      - name: p_sr
      - name: p_capitalgiro
      - name: p_ativocirculante
      - name: giroativos
      - name: roe
      - name: roa
      - name: roic
      - name: dividaliquidapatrimonioliquido
      - name: dividaliquidaebit
      - name: pl_ativo
      - name: passivo_ativo
      - name: liquidezcorrente
      - name: peg_ratio
      - name: receitas_cagr5
      - name: vpa
      - name: lpa
      - name: valormercado
      - name: segmentid
      - name: sectorid
      - name: subsectorid
      - name: dy
        tests:
          - not_null
      - name: lucros_cagr5
        tests:
          - not_null
      - name: market
