select
    ticker,
    companyname,
    price,
    p_l,
    p_vp,
    p_ebit,
    p_ativo,
    ev_ebit,
    margembruta,
    margemebit,
    margemliquida,
    p_sr,
    p_capitalgiro,
    p_ativocirculante,
    giroativos,
    roe,
    roa,
    roic,
    dividaliquidapatrimonioliquido,
    dividaliquidaebit,
    pl_ativo,
    passivo_ativo,
    liquidezcorrente,
    peg_ratio,
    receitas_cagr5,
    vpa,
    lpa,
    valormercado,
    segmentid,
    sectorid,
    subsectorid,
    coalesce(dy, 0) as dy,
    coalesce(lucros_cagr5,0) as lucros_cagr5,
    'BR' as market
from raw_layer.brazilian_stocks
