# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: admin
      password: admin
      port: 5433
      dbname: analytics
      schema: dbt_alice
      threads: 4
