DF_DTYPE = {
    "brazilian_stocks": {
        "companyid": "int64",
        "companyname": "object",
        "ticker": "object",
        "price": "float64",
        "p_l": "float64",
        "p_vp": "float64",
        "p_ebit": "float64",
        "p_ativo": "float64",
        "ev_ebit": "float64",
        "margembruta": "float64",
        "margemebit": "float64",
        "margemliquida": "float64",
        "p_sr": "float64",
        "p_capitalgiro": "float64",
        "p_ativocirculante": "float64",
        "giroativos": "float64",
        "roe": "float64",
        "roa": "float64",
        "roic": "float64",
        "dividaliquidapatrimonioliquido": "float64",
        "dividaliquidaebit": "float64",
        "pl_ativo": "float64",
        "passivo_ativo": "float64",
        "liquidezcorrente": "float64",
        "peg_ratio": "float64",
        "receitas_cagr5": "float64",
        "liquidezmediadiaria": "float64",
        "vpa": "float64",
        "lpa": "float64",
        "valormercado": "float64",
        "segmentid": "int64",
        "sectorid": "int64",
        "subsectorid": "int64",
        "subsectorname": "object",
        "segmentname": "object",
        "sectorname": "object",
        "dy": "float64",
        "lucros_cagr5": "float64",
    },
    "us_stocks": {
        "companyid": "int64",
        "companyname": "object",
        "ticker": "object",
        "price": "float64",
        "p_l": "float64",
        "dy": "float64",
        "p_vp": "float64",
        "p_ebit": "float64",
        "p_ativo": "float64",
        "ev_ebit": "float64",
        "margembruta": "float64",
        "margemebit": "float64",
        "margemliquida": "float64",
        "p_sr": "float64",
        "p_capitalgiro": "float64",
        "p_ativocirculante": "float64",
        "giroativos": "float64",
        "roe": "float64",
        "roa": "float64",
        "roic": "float64",
        "dividaliquidapatrimonioliquido": "float64",
        "dividaliquidaebit": "float64",
        "pl_ativo": "float64",
        "passivo_ativo": "float64",
        "liquidezcorrente": "float64",
        "peg_ratio": "float64",
        "receitas_cagr5": "float64",
        "lucros_cagr5": "float64",
        "vpa": "float64",
        "lpa": "float64",
        "valormercado": "float64",
        "sectorid": "int64",
        "sectorname": "object",
        "segmentid": "int64",
        "subsectorid": "int64",
        "subsectorname": "object",
        "segmentname": "object",
    },
}


def retrieve_dtype(stock_key: str):
    return DF_DTYPE.get(stock_key, None)
